spring:
  application:
    name: happy_dogs_app
  datasource:
    url: jdbc:mysql://localhost:3308/happy_dogs_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop